### PR TITLE
fix(ImageFocalPoint): handle multi locale []

### LINKED ISSUE #1932: "Add an image to the entry first" - On localization Content having multiple locale images
Works fine with an English locale.  When I try to set the focal point on 2nd locale, it throws an error. 
image

### PR DESCRIPTION
**Pull request by kdamball**
## Purpose
Image focal point does not handle multi locale. Lets fix it

## Approach
As usual, JS `this` property bit us again. `findProperLocale` would not refer to current field and not the asset's

## Dependencies and/or References
Fixes #1932

### CODE REVIEW

File: apps/image-focal-point/src/index.js [hunk 1]
```diff
@@ -52,18 +52,18 @@ export class App extends React.Component {
     const value = e.currentTarget.value;
     this.setState({ value });
     if (value) {
-      this.props.sdk.field.setValue(value);
+      this.props.sdk.field.setValue(value, this.findProperLocale());
```
Comment (andipaetzold) [inline apps/image-focal-point/src/index.js:55]: Shouldn't the app always update itself? In which scenario do we need the locale here?

**Review by andipaetzold — APPROVED** [review]
